@startuml
'https://plantuml.com/sequence-diagram

class Products{
+products: LinkedList<item>
}
class LinkedList

Products <|-- LinkedList
LinkedList == item

class item {
+name: String
+price: double
+quantity: int
}

@enduml